### PR TITLE
test: new org dsn

### PR DESCRIPTION
**Pull request by bruno-garcia**
DSN for new test org for SDK dev.

Sorry the auto format, disabled 2 VS Code integrations still don't know which one is doing that on JS files

### CODE REVIEW

**Review by jennmueng — CHANGES_REQUESTED** [review]
Should also update to the org and project slugs here https://github.com/getsentry/sentry-react-native/blob/5ce5e2eb8086ace05b9d0b2174c48c1dba36955a/sample/utils/fetchEvent.ts#L6

**Comment by bruno-garcia** [comment]
Right, then also the auth key in the github secrets needs updating.
We need to make sure this doesn't run In PRs then (by default secrets are not available in PRs, unless you're explicitly using it in the yml)

**Comment by jennmueng** [comment]
The auth token we currently have in secrets is my own, but only with read access, so I think it should just work for the new test org. Hmm I do realize the possible security implication of running it in PRs, we can disable e2e tests for PRs then.

**Comment by bruno-garcia** [comment]
> . Hmm I do realize the possible security implication of running it in PRs, we can disable e2e tests for PRs then.

yeah please, disable it for PRs

**Pull request closed without merging**
