### PR TITLE
feat(expo): Dynamically resolve sentry-cli path in expo source maps upload script

### PR DESCRIPTION
**Pull request by krystofwoldrich**
## :loudspeaker: Type of change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description

The hardcoded path could fail for certain mono repo scenarios and also for our own sample application.

## :green_heart: How did you test it?
sample app

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Review by lucas-zimerman — APPROVED** [review]
Thanks for the PR!

**Comment by rklomp** [comment]
This is now giving me:
```
'D:\Development\MyApp\node_modules\@sentry\react-native\node_modules\@sentry\cli\bin\sentry-cli' is not recognized as an internal or external command, 
operable program or batch file.
```

 `"@sentry/cli": "^2.25.0"` is in my devDependencies and installed. `npx sentry-cli` command is working.

**Comment by JustJoostNL** [comment]
@rklomp same issue here unfortunately.

**Comment by rklomp** [comment]
I am now using `SENTRY_CLI_EXECUTABLE` and that works. But it should be possible to auto detect centry cli on windows as well.

**Comment by JustJoostNL** [comment]
Could you give an example of how you use that?

**Comment by rklomp** [comment]
I used this command in powershell.
`[System.Environment]::SetEnvironmentVariable("SENTRY_CLI_EXECUTABLE","npx sentry-cli","User")`

Just google how to set environment variable in windows

**Comment by JustJoostNL** [comment]
Thanks!

**Pull request merged**
