### PR TITLE
feat(sdk): Add JS Core metrics

### PR DESCRIPTION
**Pull request by krystofwoldrich**
## :loudspeaker: Type of change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Adds JS metrics to RN.

## :bulb: Motivation and Context

closes: https://github.com/getsentry/sentry-react-native/issues/3578

## :green_heart: How did you test it?
sample apps

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Review by bruno-garcia — APPROVED** [review]
nice being able to leverage core JS!

**Comment by krystofwoldrich** [comment]
- docs https://github.com/getsentry/sentry-docs/pull/9119

**Review by lucas-zimerman — APPROVED** [review]
LGTM!

**Comment by krystofwoldrich** [comment]
- blocked by https://github.com/getsentry/sentry-react-native/pull/3592

**Pull request merged**
