### PR TITLE
chore(samples): update expo sample to SDK 52

### PR DESCRIPTION
**Pull request by krystofwoldrich**
## :loudspeaker: Type of change

- [x] Refactoring

## :scroll: Description

This PR bumps the Expo sample to the latest SDK 52.

#skip-changelog

### CODE REVIEW

**Review by antonis — APPROVED** [review]
The changes LGMT and the sample app worked as expected in all platforms 🎉

**Review by lucas-zimerman — APPROVED** [review]
LGTM!

**Comment by lucas-zimerman** [comment]
main with conflict with different versions on the packages, I have chosen the latest packages between both main and the PR

**Comment by krystofwoldrich** [comment]
@lucas-zimerman Fixed it in https://github.com/getsentry/sentry-react-native/pull/4279/commits/687023e40c0070c754f9f4e4f388048f7a29ba92 it was just a bad merge

**Pull request merged**
