### PR TITLE
feat(ReactNativeClientOptions): Remove "tunnel" option

### PR DESCRIPTION
**Pull request by AliReza99**
Remove the "tunnel" option from the ReactNativeClientOptions type due to lack of support in React Native.

This pull request removes the "tunnel" option from the ReactNativeClientOptions type. While passing this option currently does not create issues, its presence can cause confusion, leading developers to believe that the feature works when it does not. Removing it ensures clarity and avoids potential misunderstandings in React Native projects.

### CODE REVIEW

**Comment by AliReza99** [comment]
https://github.com/getsentry/sentry-react-native/issues/3258

**Comment by krystofwoldrich** [comment]
Hi @AliReza99,
thank you for the PR, we agree having the option when it's not supported is confusing.

**Comment by AliReza99** [comment]
Thanks for your response, @krystofwoldrich .

I appreciate your understanding of the confusion caused by the unsupported "tunnel" option.

Removing the "tunnel" type is crucial because its presence leads developers to debug their apps unnecessarily, given the lack of documentation indicating its unsupported status. This change helps to streamline the development process by preventing wasted time and effort.

**Comment by krystofwoldrich** [comment]
I pulled your changes and fixed the build and added changelog.

- https://github.com/getsentry/sentry-react-native/pull/3787

**Pull request closed without merging**
