### PR TITLE
Respect sentryOption.debug setting instead of #DEBUG build flag for outputting logs

### PR DESCRIPTION
**Pull request by jpotts18**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Instead of using a build flag of #DEBUG the code should respect the variable set by user in the sentryOptions.debug.

## :bulb: Motivation and Context

We have are putting a pretty large payload into our context, it is filling up our logs and we have to go comment out the` NSLog("Contexts: %")` in our code to get around this. 

## :green_heart: How did you test it?

I didnt 🤷 

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps

Decide if you want it or not. This is a Take it or leave it PR, I won't be doing followup changes.

### CODE REVIEW

**Review by jennmueng — APPROVED** [review]
Makes sense to me for the contexts to only be logged depending on the debug option instead, Thanks!

**Comment by jpotts18** [comment]
Things I wish I had done:
* Not sure if sentryOptions could be null

**Comment by marandaneto** [comment]
@jpotts18 thanks for doing this, please an entry to the changelog file.

**Comment by marandaneto** [comment]
> @jpotts18 thanks for doing this, please an entry to the changelog file.

@jpotts18 ping :)

**Review by marandaneto — APPROVED** [review]

**Pull request merged**
