### PR TITLE
feat: Support setting maxCacheItems

### PR DESCRIPTION
**Pull request by marandaneto**
## :loudspeaker: Type of change

- [ ] Bugfix
- [X] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description
feat: Support setting maxCacheItems

## :bulb: Motivation and Context
https://github.com/getsentry/sentry-react-native/issues/1452

## :pencil: Checklist

- [X] I reviewed submitted code
- [ ] I added tests to verify changes
- [X] All tests passing
- [X] No breaking changes

### CODE REVIEW

**Review by bruno-garcia — APPROVED** [review]
We need to find out way to test stuff here

**Comment by marandaneto** [comment]
> We need to find out way to test stuff here

Yep, https://github.com/getsentry/sentry-react-native/issues/1874
Just need to prioritize that.

**Comment by bruno-garcia** [comment]
We don't need to add unit tests. In fact, I believe ideally we would test this with integration or e2e tests.
e2e already exist

**Comment by marandaneto** [comment]
> We don't need to add unit tests. In fact, I believe ideally we would test this with integration or e2e tests. e2e already exist

This is just passing custom configuration to the Native SDKs, if you want to test the "maxCacheItems" feature, the Native SDKs already do it.
IMO, this type of change, only a unit test would be fine.
@philipphofmann opinions? Since we both discussed about #1874

**Pull request merged**
