### PR TITLE
 Fix(V6): Implement fallback system to screens that aren't reporting on the native layer the time to display. #4042 

### LINKED ISSUE #3934: Manual TTID/TTFD API times out
**Platform:**
- [x]  iOS

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.22.0

**`react-native` version:** 0.72.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

```
export const routingInstrumentation = new Sentry.ReactNavigationInstrumentation(
  {
    enableTimeToInitialDisplay: true,
  },
);


Sentry.init({
  environment: 'development'
  sampleRate: 1.0,
  tracesSampleRate: 0.1,
  enableAppHangTracking: false,
  integrations: [
    new Sentry.ReactNativeTracing({
      routingInstrumentation,
      tracePropagationTargets: [currentConfig.DOMAIN],
    }),
  ],
});
```
---
**I have the following issue:**

I am seeing some inconsistencies in the data reported and what should be reported based on the SDK behaviour. For example, it is odd to me that some transactions are being marked as '***deadline_exceeded***' when they do not exceed the default value for [[finalTimeoutMs](https://github.com/getsentry/sentry-react-native/blob/main/src/js/tracing/reactnativetracing.ts#L61)]. `finalTimeoutMs` is also not being overridden in the init code block

The default for `finalTimeoutMs` is 600000ms or 10mins, which is way above what the transactions being marked deadline_exceeded are reporting. The amount of failed transactions with this status seems to have increased after updating the SDK version from `5.3.0` to `5.22.0`

More details with links to examples in the [Customer Case](https://www.notion.so/sentry/Increase-in-deadline_exceeded-after-upgrade-9d472c310520417eb9ed4ab72a554dcc?pvs=4)

### PR DESCRIPTION
**Pull request by lucas-zimerman**
This is a port of https://github.com/getsentry/sentry-react-native/pull/4042 to V6

Tested on Android/iOS:
https://sentry-sdks.sentry.io/performance/trace/b0125a1564324d17b42156b5edbd4555/?dataset=transactions&field=title&field=project&field=user.display&field=timestamp&field=replayId&field=transaction.duration&fov=0%2C1910.000244140625&id=21705&name=&node=txn-ccda2e67a35c486d801315ad5c5020d9&node=txn-48c53c8b7b4a4335a12082cd81adba27&project=5428561&query=&queryDataset=transaction-like&sort=-timestamp&source=discover&statsPeriod=24h&timestamp=1729179000&topEvents=5&yAxis=count%28%29

https://sentry-sdks.sentry.io/performance/trace/514b002f17874570b2f016f0f78b9953/?dataset=transactions&field=title&field=project&field=user.display&field=timestamp&field=replayId&fov=0%2C75.13809204101562&id=21705&name=&node=span-87836929b3543124&node=txn-400cebc647684a688c5355197859dd40&project=5428561&query=&queryDataset=transaction-like&sort=-timestamp&source=discover&statsPeriod=1h&timestamp=1729198686&topEvents=5&yAxis=count%28%29
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Context: the current native implementation doesn't always emit the required event in order to track the required time to display to be set on the time to display span. 

To fix that, I introduced an additional fallback emitter, in short, it reuses the same flow by emitting the original [event](https://github.com/getsentry/sentry-react-native/pull/4042/files#diff-2b6b8eb3a7668d3a9f076a37f76f1b330c5c4219ab8c08afa5ed4c9609535a76R61) when the fallback emitter received the notification that the page was rendered and the original emitter didn't emit any event on the following 3 seconds.

With those changes, we have the following benefits:
- Support for React Native web by also having the JavaScript fallback of [requestAnimationFrame](https://reactnative.dev/docs/timers).
- Greatly reduces the wrong time to display end timestamp by having a fallback when the original implementation doesn't return any event.
- Fallback to the JavaScript implementation in case both Native emitters fail.

## :bulb: Motivation and Context

Close #3934, https://github.com/getsentry/sentry-react-native/issues/3809

## :green_heart: How did you test it?

The playground tab on our sample is a good case for testing, since it doesn't use navigation stack on it, the events on this condition are limited, not generating and required event by us in order to track the time to display.

I used it and other tabs to compare the difference between the original implementation and also `requestAnimationFrame`, and the time difference between each other was quite low:

1St Tab
JS: requestAnimationFrame, "newFrameTimestampInSeconds" is 1724293664.8300002
Original: InitAsync Event received {"newFrameTimestampInSeconds":1724293664.8179998}

2Nd Tab
JS: requestAnimationFrame, "newFrameTimestampInSeconds" is 1724293761.688
Original: InitAsync Event received {"newFrameTimestampInSeconds":1724293761.689}

3Rd Tab
JS: requestAnimationFrame, "newFrameTimestampInSeconds" is 1724293824.887
Original: Android didn't emit an event for this page so it wasn't measured

Before this change on the playground screen:
https://sentry-sdks.sentry.io/performance/trace/10bd4bf28052404592f408f3cf58175a/?dataset=transactions&field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&fov=0%2C15046.88916015625&id=21705&name=&node=trace-root&project=5428561&query=&queryDataset=transaction-like&sort=-timestamp&source=discover&statsPeriod=1h&timestamp=1724358725&topEvents=5&yAxis=count%28%29

After this change on the playground screen:
https://sentry-sdks.sentry.io/performance/trace/8cb478b4370e444fa4a7b9be778d51ab/?dataset=transactions&field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&fov=0%2C235&id=21705&name=&node=txn-b5a8ba18aa254fe79743133baf9071b2&project=5428561&query=&queryDataset=transaction-like&sort=-timestamp&source=discover&statsPeriod=1h&timestamp=1724359145&topEvents=5&yAxis=count%28%29

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled
- [ ] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by lucas-zimerman** [comment]
moving to draft until CI is fixed

**Comment by lucas-zimerman** [comment]
Too bad yarn lint gives unuseful information offline but CI is now passing
```
Executing: npx google-java-format --set-exit-if-changed --glob='samples/react-native/android/app/src/**/*.java'
Executing: npx google-java-format --set-exit-if-changed --glob='packages/core/android/**/*.java'
Error: google-java-format exited with exit code 1.
    at errorFromExitCode (/run/media/mario/bda233cc-061c-4aa4-af24-cbb92451e918/Dev/Sentry/sentry-react-native/node_modules/google-java-format/index.js:19:10)
    at ChildProcess.<anonymous> (/run/media/mario/bda233cc-061c-4aa4-af24-cbb92451e918/Dev/Sentry/sentry-react-native/node_modules/google-java-format/index.js:111:40)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
Command failed: npx google-java-format --set-exit-if-changed --glob='packages/core/android/**/*.java'
Executing: npx google-java-format --set-exit-if-changed --glob='performance-tests/TestAppPlain/android/app/src/**/*.java'
Executing: npx google-java-format --set-exit-if-changed --glob='performance-tests/TestAppSentry/android/app/src/**/*.java'
One or more commands failed.
ERROR: "java:format lint" exited with 1.
ERROR: "lint:android" exited with 1.
```

**Review by antonis — APPROVED** [review]
LGTM 🚀 
Thank you for porting the implementation to v6 🙇

**Comment by krystofwoldrich** [comment]
> Too bad yarn lint gives unuseful information offline but CI is now passing

Yeah, sadly the google formater doesn't include any output. You can run fix and than check git on what changed. 

In CI we print the changed automatically.

**Pull request merged**
