### PR TITLE
chore(ci): Stop updating wizard and cli on main (v4) branch

### PR DESCRIPTION
**Pull request by krystofwoldrich**
Temporarily remove wizard and cli updater.

When v5 is merged to the main these jobs will be back from that branch and PR will be opened automatically again.

#skip-changelog

### CODE REVIEW

**Comment by marandaneto** [comment]
@krystofwoldrich What's the reason for removing it?

**Comment by krystofwoldrich** [comment]
@marandaneto To clean up the PRs, if we remove it from the main branch it will pause the PRs (which can't be closed at the moment, since the updater is opening them), and then when v5 will be merged back the updater will be back.

**Comment by marandaneto** [comment]
> @marandaneto To clean up the PRs, if we remove it from the main branch it will pause the PRs (which can't be closed at the moment, since the updater is opening them), and then when v5 will be merged back the updater will be back.

Maybe just comment out then? When merging v5, it might be that it is removed in the diff, with a comment, you can undo at least.

**Comment by krystofwoldrich** [comment]
> > @marandaneto To clean up the PRs, if we remove it from the main branch it will pause the PRs (which can't be closed at the moment, since the updater is opening them), and then when v5 will be merged back the updater will be back.
> 
> Maybe just comment out then? When merging v5, it might be that it is removed in the diff, with a comment, you can undo at least.

Okay, that makes sense, it will be easier to return it.

**Review by marandaneto — APPROVED** [review]

**Pull request merged**
