### PR TITLE
Add `androidx` support.

### PR DESCRIPTION
**Pull request by jgreen01su**
- Replace `android.support` with `androidx` in import.

### CODE REVIEW

**Comment by maieonbrix** [comment]
Hello :) 

Maybe we can simply remove the annotation ? Like what you did here : https://github.com/itinance/react-native-fs/pull/691

Just to ensure the two-ways compatibility.

**Comment by jgreen01su** [comment]
Thanks @maieonbrix and @se-bastiaan ! I removed the annotation and androidx import.

**Comment by HazAT** [comment]
Thanks for this. We just released beta version of the new version of our SDK which has the fix already in there.
See: https://github.com/getsentry/sentry-react-native/issues/612

If really necessary I can make a patch release.

**Comment by se-bastiaan** [comment]
I think that completely depends on the planning for the v1 of the SDK. I would say that this, as a breaking change, is the perfect moment to only support react-native v0.60 and higher as you already mentioned in #612. However, if v1 takes longer than expected it would be nice to have a patch release. For now, no need imo. We'll have to wait for other packages and their updates to be able to update to RN 0.60 anyways.

**Comment by muhammadsr** [comment]
Can we merge this PR?

**Comment by HazAT** [comment]
I will close this PR since it's outdaten, please migrate / use our new SDK which has support for AndroidX
https://github.com/getsentry/sentry-react-native/issues/612

**Pull request closed without merging**
