### PR TITLE
misc: Update CONTRIBUTING.md for the monorepo changes

### PR DESCRIPTION
**Pull request by krystofwoldrich**
#skip-changelog

### CODE REVIEW

**Comment by antonis** [comment]
l: Adding a note on a minor issue I encountered. I think the `yarn run-android` and `yarn run-ios` on the [Run the emulators sections](https://github.com/getsentry/sentry-react-native/blob/kw/update-contributing-guide/CONTRIBUTING.md#run-the-emulators-legacy-architecture) should be changed to `yarn android` and `yarn ios` to match [the scripts of the samples](https://github.com/getsentry/sentry-react-native/blob/v6/samples/react-native/package.json#L7).
I'll be glad to open a separate PR for this but thought of adding a note on this related PR 1st.

**Comment by lucas-zimerman** [comment]
I like the idea of both samples and main SDK having the same script name for running the ios/android samples

**Review by antonis — APPROVED** [review]
LGTM 🚀 
I will revisit [my comment](https://github.com/getsentry/sentry-react-native/pull/4087#issuecomment-2357971906) and open a separate PR since it escapes the scope of the introduced changes.

**Comment by antonis** [comment]
> I will revisit https://github.com/getsentry/sentry-react-native/pull/4087#issuecomment-2357971906 and open a separate PR since it escapes the scope of the introduced changes.

Followed up on this here with a suggested change https://github.com/getsentry/sentry-react-native/pull/4133

**Pull request merged**
