### PR TITLE
Fix issue with Sentry React Native SDK's enableNative variable

### PR DESCRIPTION
**Pull request by mateioprea**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

This commit addresses a problem with the Sentry React Native SDK where the this.enableNative variable was not correctly reinitialized to true after reinitializing the SDK. The issue arose when calling the `closeNativeSdk()` method, which set `this.enableNative` to `false`. Without reinitializing it to true, subsequent reinitializations of the SDK would prevent stopping the SDK afterwards.

To fix this, I added a line in the initNativeSdk function to explicitly set `this.enableNative = true` after reinitializing the native SDK.

This change resolves the problem and ensures that the enableNative variable is properly managed during SDK reinitialization, allowing for the correct functioning of the Sentry React Native SDK.

## :bulb: Motivation and Context

The motivation behind this change is to ensure that the enableNative variable is correctly managed during SDK reinitialization, allowing for the proper functioning of the Sentry React Native SDK.

This change fixes the issue and ensures that the enableNative variable is reset to true after reinitializing the native SDK, thereby enabling the native SDK functionality as intended.

## :green_heart: How did you test it?

I conducted testing of this change on my local application to ensure its effectiveness. The following steps were taken during the testing process:

1. Set up a local development environment with the Sentry React Native SDK integrated into my application.
2. Created a scenario where the closeNativeSdk() method is called to disable the native SDK and subsequently attempted to reinitialize the SDK.
3. Verified that prior to the change, the enableNative variable was not reinitialized to true after reinitializing the SDK, leading to the native SDK functionality not being enabled.
4. Applied the proposed change to the codebase, which includes resetting the enableNative variable to true in the initNativeSdk function.
5. Repeated the scenario where the closeNativeSdk() method is called and then attempted to reinitialize the SDK.
6. Verified that after applying the change, the enableNative variable was correctly reinitialized to true, enabling the native SDK functionality upon reinitialization.
7. Conducted additional testing by calling the closeNativeSdk() method again after reinitializing the SDK.
8. Ensured that the native SDK was successfully stopped and disabled as expected, preventing any further native SDK functionality.
9. Ensured that the rest of the application's functionality remained unaffected by the change.
10. By following these steps and observing the expected behavior, I confirmed that the change effectively resolves the issue with the enableNative variable and allows for subsequent reinitializations of the SDK while still being able to stop and disable the native SDK when desired.

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled
- [ ] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the PR and the detailed description.

Since this is mainly a matter of handling the `enableNative` flag, could you please update the tests in [`wrapper.test.ts`](https://github.com/getsentry/sentry-react-native/blob/d18788726b6656377de1365256be859672d6436f/test/wrapper.test.ts#L134)

Here https://github.com/getsentry/sentry-react-native/blob/d18788726b6656377de1365256be859672d6436f/test/wrapper.test.ts#L133-L134
```diff

    test('does not initialize with autoInitializeNativeSdk: false', async () => {
+      NATIVE.enableNative = false;
      logger.warn = jest.fn();
```

and https://github.com/getsentry/sentry-react-native/blob/d18788726b6656377de1365256be859672d6436f/test/wrapper.test.ts#L490-L491

```diff
    test('closeNativeSdk calls native bridge', async () => {
+      NATIVE.enableNative = true;
      await NATIVE.closeNativeSdk();
```

**Comment by mateioprea** [comment]
@krystofwoldrich thank you! I just pushed a fix for that.

**Comment by mateioprea** [comment]
@krystofwoldrich i don't understand why the e2e tests are failing now. everything should be good. 
But I see that some tests don't even get to the relevant phase, like: 
`[RnDiffApp] Running script Upload Debug Symbols to Sentry`
or 
`Error cloning certificates git repo, please make sure you have access to the repository - see instructions above`

**Comment by krystofwoldrich** [comment]
@mateioprea The e2e build tests fail because the auth tokens are missing for the community PR. The tests fail on uploading the source maps. But that is okay.

**Comment by mateioprea** [comment]
> @mateioprea The e2e build tests fail because the auth tokens are missing for the community PR. The tests fail on uploading the source maps. But that is okay.

ok. perfect. so is this something else that I should this on this PR?

**Comment by mateioprea** [comment]
@krystofwoldrich thank you for guidance. I've updated the files accordingly.

**Review by krystofwoldrich — APPROVED** [review]
Thank you for the PR and the work. 🚀

**Comment by mateioprea** [comment]
Thank you @krystofwoldrich. Have a great day!

**Pull request merged**
